services: 
  redis: 
    container_name: redis-tomoon
    image: redis
    ports: 
      - 6379:6379
    restart: always

  app:
    build: .
    container_name: api-tomoon
    restart: always
    ports: 
      - 6666:6666
    volumes: 
      - .:/usr/app
    links: 
      - redis
    depends_on: 
      - redis